root: true
extends:
  - plugin:import/recommended
plugins:
  - "@nx"
settings:
  import/resolver:
    typescript: true
    node: true
parserOptions:
  EXPERIMENTAL_useProjectService: true
rules:
  import/no-cycle:
    - error
  import/order:
    - warn
    - groups:
        - builtin
        - external
        - object
overrides:
  - files:
      - "*.ts"
      - "*.tsx"
      - "*.js"
      - "*.jsx"
    rules:
      "@nx/enforce-module-boundaries":
        - error
        - enforceBuildableLibDependency: true
          allow: []
          depConstraints:
            - sourceTag: "*"
              onlyDependOnLibsWithTags:
                - "*"
  - files:
      - "*.ts"
      - "*.tsx"
    extends:
      - plugin:@nx/typescript
    rules:
      import/no-cycle:
        - error
  - files:
      - "*.js"
      - "*.jsx"
    extends:
      - plugin:@nx/javascript
    rules: {}
  - files:
      - "*.spec.ts"
      - "*.spec.tsx"
      - "*.spec.js"
      - "*.spec.jsx"
    env:
      jest: true
    rules: {}
