name: Release
on:
  workflow_call:
    secrets:
      NPM_TOKEN:
        required: true

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm exec nx run-many -t test --coverage
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_AUTOMATION }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: pnpx semantic-release
      - name: Upload Code Coverage
        uses: codecov/codecov-action@v3.1.0
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
