name: Release
on:
  workflow_call:
    secrets:
      NPM_TOKEN:
        required: true

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.5.0
      - name: Install PNPM & NX
        run: npm run setup:globals
      - name: Install dependencies
        run: pnpm i
      - name: Build
        run: nx run-many -t build
      - name: Test
        run: nx run-many -t test
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_AUTOMATION }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
      - name: Upload Code Coverage
        uses: codecov/codecov-action@v3.1.0
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
